name: Render UML Diagram with PlantUML

on:
  push:
    paths:
      - client/prisma/uml.pu

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-docker@v1
    
    - name: Run PlantUML Docker container
      run: |
        docker run --rm -v $(pwd):/data ghcr.io/plantuml/plantuml -tsvg uml.pu
        docker run --rm -v $(pwd):/data ghcr.io/plantuml/plantuml -tpng uml.pu

    - uses: EndBug/add-and-commit@v9
      with:
        add: client/prisma/uml.svg
        default_author: github_actions
        message: Update DB UML Diagram
