name: Update DB UML Diagram

on:
  push:
    paths:
      - client/prisma/uml.pu

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/plantuml/plantuml
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run plantuml
        run: plantuml -tsvg client/prisma/uml.pu

      - uses: EndBug/add-and-commit@v9
        with:
          add: client/prisma/uml.svg
          default_author: github_actions
          message: Update DB UML Diagram
