# Shamelessly stolen (with permission) from @probably-neb
name: Update DB UML Diagram

on:
  push:
    paths:
      - client/prisma/schema.prisma
      - client/prisma/README.md

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prisma-uml
        run: npm install prisma-uml

      - name: Run prisma-uml
        # relationMode isn't recognized by prisma-uml so this is hacking around that
        run: temp=$(mktemp) &&
          sed -e 's/relationMode *= *"prisma"/\/\/ \0/g' client/prisma/schema.prisma > $temp &&
          npx prisma-uml $temp -o svg -f client/prisma/uml.svg

      - uses: EndBug/add-and-commit@v9
        with:
          add: client/prisma/uml.svg
          default_author: github_actions
          message: Update DB UML Diagram
