# Shamelessly stolen (with permission) from @probably-neb
name: Update DB UML Diagram

on:
  push:
    paths:
      - client/prisma/schema.prisma
      - client/prisma/README.md

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prisma-uml
        run: npm install prisma-uml

      - name: Run prisma-uml
        run: npx prisma-uml client/prisma/schema.prisma -o png -f client/prisma/uml.png

      - uses: EndBug/add-and-commit@v9
        with:
          add: client/prisma/uml.png
          default_author: github_actions
          message: Update DB UML Diagram
